package com.github.kitakkun.orenon.tool

import com.squareup.kotlinpoet.*

class AstClassGenerator {
    private val exprClassName = ClassName("com.github.kitakkun.orenon", "Expr")
    private val tokenClassName = ClassName("com.github.kitakkun.orenon", "Token")

    private val exprClassSpecs = listOf(
        ExprClassSpec(
            name = "Binary",
            properties = mapOf(
                "left" to exprClassName,
                "right" to exprClassName,
                "operator" to tokenClassName,
            )
        ),
        ExprClassSpec(
            name = "Grouping",
            properties = mapOf(
                "expression" to exprClassName,
            )
        ),
        ExprClassSpec(
            name = "Literal",
            properties = mapOf(
                "value" to Any::class.asClassName()
            )
        ),
        ExprClassSpec(
            name = "Unary",
            properties = mapOf(
                "operator" to tokenClassName,
                "right" to exprClassName,
            )
        )
    )

    data class ExprClassSpec(
        val name: String,
        val properties: Map<String, ClassName>,
    )

    fun generate(): FileSpec {
        val file = FileSpec.builder("com.github.kitakkun.orenon", "Expr")
            .addFileComment(
                """
                This code is automatically generated by program. DO NOT EDIT.
                """.trimIndent()
            )
            .addType(
                TypeSpec.classBuilder(exprClassName)
                    .addModifiers(KModifier.SEALED)
                    .addTypes(
                        exprClassSpecs.map { spec ->
                            val propertySpecs = spec.properties.map { (name, className) ->
                                PropertySpec.builder(name, className)
                                    .initializer(name)
                                    .build()
                            }
                            val parameterSpecs = spec.properties.map { (name, className) ->
                                ParameterSpec.builder(name, className).build()
                            }
                            TypeSpec.classBuilder(spec.name)
                                .addModifiers(KModifier.DATA)
                                .superclass(exprClassName)
                                .addProperties(propertySpecs)
                                .primaryConstructor(
                                    FunSpec.constructorBuilder()
                                        .addParameters(parameterSpecs)
                                        .build()
                                )
                                .build()
                        }
                    )
                    .build()
            )
            .build()

        return file
    }
}
